# Conclusion

## Results

In [3]:
import pandas as pd

In [8]:
pd.read_csv('fig/Model_comparison.csv', index_col=0)

,(5 Rec) R_precision,(5 Rec) NDCG,(50 Rec) R_precision,(50 Rec) NDCG,(200 Rec) R_precision,(200 Rec) NDCG,(500 Rec) R_precision,(500 Rec) NDCG
Top500,0.004654,0.010397,0.006192,0.014750,0.006192,0.028965,0.006192,0.043392
User_to_user,0.030185,0.071811,0.050142,0.086790,0.050142,0.124019,0.050142,0.147755
Item_to_item,0.005436,0.006855,0.006113,0.009361,0.006113,0.016136,0.006113,0.026642
ALS,0.035194,0.080131,0.058561,0.095977,0.058561,0.135142,0.058561,0.155013
KNN,0.030185,0.071811,0.050529,0.087356,0.050529,0.124487,0.050529,0.147901
NN,0.016574,0.035461,0.024119,0.038996,0.024119,0.059876,0.024119,0.072938

In [6]:
pd.read_csv('fig/ALS_comparision.csv', ind$$ex_col=0)

,(5 Rec) R_precision,(5 Rec) NDCG,(50 Rec) R_precision,(50 Rec) NDCG,(200 Rec) R_precision,(200 Rec) NDCG,(500 Rec) R_precision,(500 Rec) NDCG
ALS_1K,0.035194,0.080131,0.058561,0.095977,0.058561,0.135142,0.058561,0.155013
ALS_3K,0.042672,0.109835,0.074360,0.135022,0.074360,0.178821,0.074360,0.203307
ALS_5K,0.046568,0.123241,0.082436,0.148563,0.082436,0.202287,0.082436,0.232798
ALS_7K,0.059178,0.153416,0.099179,0.173437,0.099179,0.225403,0.099179,0.252059
ALS_10K,0.057507,0.147706,0.098422,0.171526,0.098422,0.222237,0.098422,0.247855

## Conclusion/Discussion

## Future Works

## References